### ISSUE TITLE
I have the same issue with you how can I reach you?

### ISSUE THREAD

**Issue by NguyenAnhTuan1912** [fabseven/nix-darwin#1]
I have the same issue with you __Deploy a Slack gateway for Amazon Q Business__ , your issue here: [https://github.com/aws-samples/amazon-q-slack-gateway/issues/49](https://github.com/aws-samples/amazon-q-slack-gateway/issues/49).

I enable IAM Identity Center in Singapore and my Amazon Q app in N.Virginia. How can you fix that?

**Comment by fabseven** [comment]
@NguyenAnhTuan1912 Hello, the issue was that I had our IAM Identity Center in eu-west-1 (Ireland) and Q app in us-east-1 (N.Virginia) like you.

I had to create a new account IAM identiy center instance in us-east-1 for it to work properly so your IAM & Q have to be in the same region.

**Comment by NguyenAnhTuan1912** [comment]
@fabseven Thank you so much
